allowBuilds:
  esbuild: true
  '@shimpz/frontend@https://codeload.github.com/TheShimpz/shimpz-frontend/tar.gz/31b6b088de4bc70ea2674b238e788c6227807771': true

overrides:
  cookie: 0.7.2
  nanoid: 3.3.18
  postcss: 8.5.23
