allowBuilds:
  esbuild: true
  '@shimpz/frontend@https://codeload.github.com/TheShimpz/shimpz-frontend/tar.gz/c726ca1898f14ce2ae68a0fc24c6dd7937b85fce': true
  '@shimpz/frontend@https://codeload.github.com/TheShimpz/shimpz-frontend/tar.gz/ffa73813f3a0e65fe4a38f633502099aeb5e317d': set this to true or false

overrides:
  cookie: 0.7.2
  nanoid: 3.3.18
  postcss: 8.5.23
