import type { Locale } from "$lib/locales";

export type Concept = { title: string; body: string };

export type InstitutionalPageContent = {
  seoTitle: string;
  seoDescription: string;
  kicker: string;
  title: string;
  lead: string;
  sections: Concept[];
  noteTitle: string;
  noteBody: string;
};

export type InstitutionalPage = "openSource" | "about";
type PageTuple = [string, string, string, [string, string][], string, string];

function buildPages(input: Record<Locale, PageTuple>): Record<Locale, InstitutionalPageContent> {
  return Object.fromEntries(Object.entries(input).map(([locale, [kicker, title, lead, sections, noteTitle, noteBody]]) => [
    locale,
    {
      seoTitle: `${title} · Shimpz`,
      seoDescription: lead,
      kicker,
      title,
      lead,
      sections: sections.map(([sectionTitle, body]) => ({ title: sectionTitle, body })),
      noteTitle,
      noteBody,
    },
  ])) as Record<Locale, InstitutionalPageContent>;
}

const PAGE_CONTENT: Record<InstitutionalPage, Record<Locale, InstitutionalPageContent>> = {
  openSource: buildPages({
    en: ["Open source // inspect the work", "Open where trust needs evidence.", "Shimpz is an open-source organization. Public repositories expose the platform implementation and its reviewable history without granting any Assistant a privileged path.", [["Independent repositories", "Account, Admin, Assistants platform responsibilities, Brain, Browser, Developers, Docs, Services, Store, and Teams retain explicit source ownership."], ["One publication path", "Every Assistant, including Shimpz Cloudflare, is independently published through Developers, projected by Store, and authorized by Team."], ["Creator choice", "Platform openness does not claim that every Creator Assistant is open source. Each Assistant must state its own source availability honestly."]], "Inspect, do not assume", "The public website links to the exact repositories in scope. Open source never substitutes for runtime isolation, authority checks, or artifact verification."],
    pt: ["Código aberto // inspecione o trabalho", "Aberto onde a confiança precisa de evidência.", "O Shimpz é uma organização de código aberto. Repositórios públicos expõem a implementação da plataforma e seu histórico revisável sem conceder um caminho privilegiado a qualquer Assistente.", [["Repositórios independentes", "Account, Admin, responsabilidades de plataforma de Assistants, Brain, Browser, Developers, Docs, Services, Store e Teams mantêm ownership explícito do código."], ["Um caminho de publicação", "Todo Assistente, inclusive o Shimpz Cloudflare, é publicado independentemente por Developers, projetado pela Store e autorizado pelo Time."], ["Escolha do Creator", "A abertura da plataforma não afirma que todo Assistente de Creator é open source. Cada Assistente deve declarar honestamente a disponibilidade do próprio código."]], "Inspecione, não presuma", "O site público aponta para os repositórios exatos em escopo. Código aberto nunca substitui isolamento em runtime, verificação de autoridade ou de artefatos."],
    es: ["Código abierto // inspecciona el trabajo", "Abierto donde la confianza necesita pruebas.", "Shimpz es una organización de código abierto. Los repositorios públicos muestran la implementación y su historial revisable sin dar a ningún Asistente una ruta privilegiada.", [["Repositorios independientes", "Account, Admin, responsabilidades de Assistants, Brain, Browser, Developers, Docs, Services, Store y Teams mantienen ownership explícito del código."], ["Una ruta de publicación", "Cada Asistente, incluido Shimpz Cloudflare, se publica mediante Developers, se proyecta en Store y es autorizado por Team."], ["Elección del Creator", "La apertura de la plataforma no afirma que todo Asistente de un Creator sea open source. Cada Asistente declara honestamente la disponibilidad de su código."]], "Inspecciona, no supongas", "El sitio enlaza los repositorios exactos. El código abierto no sustituye el aislamiento, la autorización ni la verificación de artefactos."],
    fr: ["Open source // inspectez le travail", "Ouvert là où la confiance exige des preuves.", "Shimpz est une organisation open source. Les dépôts publics montrent l’implémentation et son historique vérifiable sans accorder de parcours privilégié à un Assistant.", [["Dépôts indépendants", "Account, Admin, responsabilités de plateforme Assistants, Brain, Browser, Developers, Docs, Services, Store et Teams conservent une ownership explicite du code."], ["Un parcours de publication", "Chaque Assistant, y compris Shimpz Cloudflare, est publié par Developers, projeté par Store et autorisé par Team."], ["Choix du Creator", "L’ouverture de la plateforme ne prétend pas que chaque Assistant de Creator est open source. Chacun déclare honnêtement la disponibilité de son code."]], "Inspectez, ne présumez pas", "Le site public relie les dépôts exacts. L’open source ne remplace jamais l’isolation, les contrôles d’autorité ou la vérification des artefacts."],
    de: ["Open Source // prüfe die Arbeit", "Offen, wo Vertrauen Belege braucht.", "Shimpz ist eine Open-Source-Organisation. Öffentliche Repositories zeigen Implementierung und prüfbare Historie, ohne einem Assistant einen Sonderweg zu geben.", [["Unabhängige Repositories", "Account, Admin, Assistant-Plattformaufgaben, Brain, Browser, Developers, Docs, Services, Store und Teams behalten eindeutige Quellverantwortung."], ["Ein Veröffentlichungsweg", "Jeder Assistant, auch Shimpz Cloudflare, wird durch Developers veröffentlicht, von Store dargestellt und von Team autorisiert."], ["Wahl des Creator", "Die offene Plattform bedeutet nicht, dass jeder Creator-Assistant Open Source ist. Jeder Assistant nennt seine Quellverfügbarkeit ehrlich."]], "Prüfen, nicht annehmen", "Die Website verlinkt die exakten Repositories. Open Source ersetzt nie Laufzeitisolation, Autoritätsprüfung oder Artefaktverifikation."],
    zh: ["开源 // 检查工作", "在信任需要证据的地方保持开放。", "Shimpz 是一个开源组织。公共仓库展示平台实现和可审查历史，同时不会为任何 Assistant 提供特权路径。", [["独立仓库", "Account、Admin、Assistant 平台职责、Brain、Browser、Developers、Docs、Services、Store 和 Teams 都有明确的源码归属。"], ["一条发布路径", "每个 Assistant，包括 Shimpz Cloudflare，都通过 Developers 独立发布，由 Store 展示，并由 Team 授权。"], ["Creator 的选择", "平台开放不代表每个 Creator Assistant 都是开源的。每个 Assistant 必须如实说明源码可用性。"]], "检查，而不是假设", "公共网站链接到准确范围内的仓库。开源不能替代运行时隔离、授权检查或制品验证。"],
    ja: ["オープンソース // 実装を確認", "信頼に証拠が必要な場所を公開する。", "Shimpz はオープンソース組織です。公開リポジトリで実装と確認可能な履歴を示しつつ、どの Assistant にも特別な経路を与えません。", [["独立したリポジトリ", "Account、Admin、Assistant プラットフォーム責任、Brain、Browser、Developers、Docs、Services、Store、Teams は明示的なソース所有を保ちます。"], ["一つの公開経路", "Shimpz Cloudflare を含む全 Assistant は Developers から独立公開され、Store に表示され、Team によって承認されます。"], ["Creator の選択", "プラットフォームが開かれていても、すべての Creator Assistant がオープンソースとは限りません。各 Assistant がソース公開状況を正直に示します。"]], "推測せず確認する", "公開サイトは対象となる正確なリポジトリにリンクします。オープンソースは実行時分離、権限確認、制品検証の代わりにはなりません。"],
    ar: ["مفتوح المصدر // افحص العمل", "مفتوح حيث تحتاج الثقة إلى دليل.", "Shimpz منظمة مفتوحة المصدر. تعرض المستودعات العامة تنفيذ المنصة وتاريخه القابل للمراجعة دون منح أي Assistant مسارًا مميزًا.", [["مستودعات مستقلة", "تحتفظ Account وAdmin ومسؤوليات منصة Assistants وBrain وBrowser وDevelopers وDocs وServices وStore وTeams بملكية مصدر واضحة."], ["مسار نشر واحد", "تُنشر كل Assistant، بما فيها Shimpz Cloudflare، بصورة مستقلة عبر Developers وتعرضها Store وتصرح بها Team."], ["اختيار Creator", "انفتاح المنصة لا يعني أن كل Assistant ينشئها Creator مفتوحة المصدر. تصف كل Assistant توفر مصدرها بصدق."]], "افحص ولا تفترض", "يربط الموقع بالمستودعات الدقيقة ضمن النطاق. لا يحل المصدر المفتوح محل عزل التشغيل أو فحوص السلطة أو التحقق من القطع."],
  }),
  about: buildPages({
    en: ["About // why Shimpz exists", "Built for presence, not for more screen time.", "Shimpz is an open-source organization founded by Juliano Amaral Gouveia from a working personal system and a simple need: useful digital work should not keep a founder attached to a notebook.", [["Sworder and Neo", "The first system connected Meta Ads, Cloudflare, and a server to an AI experience administered through Telegram. It performed useful work, but remained bespoke, reactive, and expensive to operate safely."], ["A human reason", "While Juliano’s wife was pregnant, freedom from the notebook meant something concrete: more presence with his family without abandoning responsibility for the work."], ["The Shimpz thesis", "Reasoning should coordinate bounded, reusable software instead of inventing every implementation again. Humans keep authority over access and consequential decisions."]], "An organization and a project", "Shimpz presents the company and the open-source work with one voice: precise about what exists, explicit about what is still future, and organized so the product can outlive one session or one person’s memory."],
    pt: ["Sobre // por que o Shimpz existe", "Construído para presença, não para mais tempo de tela.", "O Shimpz é uma organização de código aberto fundada por Juliano Amaral Gouveia a partir de um sistema pessoal funcional e de uma necessidade simples: trabalho digital útil não deveria prender um fundador ao notebook.", [["Sworder e Neo", "O primeiro sistema conectava Meta Ads, Cloudflare e um servidor a uma experiência de IA administrada pelo Telegram. Realizava trabalho útil, mas continuava artesanal, reativo e caro de operar com segurança."], ["Uma razão humana", "Enquanto a esposa de Juliano estava grávida, liberdade do notebook significava algo concreto: estar mais presente com a família sem abandonar a responsabilidade pelo trabalho."], ["A tese do Shimpz", "O raciocínio deve coordenar software limitado e reutilizável em vez de inventar cada implementação novamente. Humanos mantêm autoridade sobre acessos e decisões consequentes."]], "Uma organização e um projeto", "O Shimpz apresenta a empresa e o trabalho open source com uma voz: preciso sobre o que existe, explícito sobre o que ainda é futuro e organizado para que o produto sobreviva a uma sessão ou à memória de uma pessoa."],
    es: ["Acerca de // por qué existe Shimpz", "Creado para estar presente, no para pasar más tiempo frente a una pantalla.", "Shimpz es una organización de código abierto fundada por Juliano Amaral Gouveia a partir de un sistema personal funcional y una necesidad sencilla: el trabajo digital útil no debería atar a un fundador a su portátil.", [["Sworder y Neo", "El primer sistema conectó Meta Ads, Cloudflare y un servidor con una experiencia de IA administrada por Telegram. Hacía trabajo útil, pero seguía siendo artesanal, reactivo y costoso de operar de forma segura."], ["Una razón humana", "Mientras la esposa de Juliano estaba embarazada, liberarse del portátil significaba algo concreto: estar más presente con su familia sin abandonar la responsabilidad por el trabajo."], ["La tesis de Shimpz", "El razonamiento debe coordinar software limitado y reutilizable en vez de inventar cada implementación de nuevo. Los humanos conservan la autoridad sobre accesos y decisiones relevantes."]], "Una organización y un proyecto", "Shimpz presenta la empresa y el trabajo open source con una sola voz: precisa sobre lo que existe, explícita sobre el futuro y organizada para superar una sesión o la memoria de una persona."],
    fr: ["À propos // pourquoi Shimpz existe", "Conçu pour être présent, pas pour ajouter du temps d’écran.", "Shimpz est une organisation open source fondée par Juliano Amaral Gouveia à partir d’un système personnel fonctionnel et d’un besoin simple : le travail numérique utile ne devrait pas attacher un fondateur à son ordinateur.", [["Sworder et Neo", "Le premier système reliait Meta Ads, Cloudflare et un serveur à une expérience d’IA administrée via Telegram. Il produisait du travail utile, mais restait sur mesure, réactif et coûteux à exploiter de façon sûre."], ["Une raison humaine", "Pendant la grossesse de l’épouse de Juliano, se libérer de l’ordinateur signifiait être plus présent auprès de sa famille sans abandonner la responsabilité du travail."], ["La thèse Shimpz", "Le raisonnement doit coordonner des logiciels limités et réutilisables plutôt que réinventer chaque implémentation. Les humains gardent l’autorité sur les accès et décisions importantes."]], "Une organisation et un projet", "Shimpz présente l’entreprise et le travail open source d’une seule voix : précise sur l’existant, explicite sur l’avenir et organisée pour dépasser une session ou la mémoire d’une personne."],
    de: ["Über uns // warum Shimpz existiert", "Für Präsenz gebaut, nicht für mehr Bildschirmzeit.", "Shimpz ist eine von Juliano Amaral Gouveia gegründete Open-Source-Organisation. Ausgangspunkt waren ein funktionierendes persönliches System und ein einfacher Bedarf: Nützliche digitale Arbeit sollte einen Gründer nicht an sein Notebook binden.", [["Sworder und Neo", "Das erste System verband Meta Ads, Cloudflare und einen Server mit einer über Telegram verwalteten KI-Erfahrung. Es erledigte echte Arbeit, blieb aber individuell, reaktiv und teuer im sicheren Betrieb."], ["Ein menschlicher Grund", "Während Julianes Frau schwanger war, bedeutete Freiheit vom Notebook etwas Konkretes: mehr Präsenz bei der Familie, ohne Verantwortung für die Arbeit abzugeben."], ["Die Shimpz-These", "Reasoning soll begrenzte, wiederverwendbare Software koordinieren, statt jede Implementierung neu zu erfinden. Menschen behalten Autorität über Zugriffe und folgenreiche Entscheidungen."]], "Organisation und Projekt", "Shimpz spricht für Unternehmen und Open-Source-Arbeit mit einer Stimme: präzise über das Bestehende, deutlich über die Zukunft und so organisiert, dass das Produkt mehr als eine Sitzung oder Erinnerung überdauert."],
    zh: ["关于 // Shimpz 为何存在", "为了真正陪伴，而不是增加屏幕时间。", "Shimpz 是 Juliano Amaral Gouveia 创立的开源组织。它源自一个实际运行的个人系统和一个简单需求：有用的数字工作不应把创始人绑在笔记本电脑前。", [["Sworder 与 Neo", "最初的系统把 Meta Ads、Cloudflare 和服务器连接到通过 Telegram 管理的 AI 体验。它能完成真实工作，但仍是定制的、被动的，并且难以安全地规模化运营。"], ["一个人的理由", "Juliano 的妻子怀孕期间，摆脱笔记本电脑有了具体含义：在不放弃工作责任的同时，更多地陪伴家人。"], ["Shimpz 的主张", "推理应协调有边界、可复用的软件，而不是每次重新发明实现。人类保留对访问权限和关键决策的授权。"]], "一个组织，也是一个项目", "Shimpz 以同一种声音介绍公司和开源工作：准确说明已有内容，明确标记未来方向，并通过组织化让产品不依赖一次会话或一个人的记忆。"],
    ja: ["Shimpz について // なぜ存在するのか", "画面を見る時間ではなく、大切な場にいるために。", "Shimpz は Juliano Amaral Gouveia が、実際に動く個人システムと一つの必要性から設立したオープンソース組織です。有用なデジタル作業のために、創業者がノート PC に縛られるべきではありません。", [["Sworder と Neo", "最初のシステムは Meta Ads、Cloudflare、サーバーを Telegram で管理する AI 体験につなぎました。実際の仕事はできましたが、個別構築で反応的、かつ安全な運用コストが高いものでした。"], ["人としての理由", "Juliano の妻が妊娠していた時期、ノート PC からの自由には具体的な意味がありました。仕事の責任を放棄せず、家族と過ごす時間を増やすことです。"], ["Shimpz の考え", "推論は実装を毎回発明するのではなく、境界のある再利用可能なソフトウェアを調整すべきです。アクセスと重要な判断の権限は人が持ちます。"]], "組織でありプロジェクト", "Shimpz は会社とオープンソース活動を一つの声で伝えます。存在するものを正確に、未来を明示し、一度の会話や一人の記憶を超えて続くよう整理します。"],
    ar: ["حول Shimpz // لماذا وُجدت", "بُنيت للحضور، لا لمزيد من وقت الشاشة.", "Shimpz منظمة مفتوحة المصدر أسسها Juliano Amaral Gouveia انطلاقًا من نظام شخصي عامل وحاجة بسيطة: لا ينبغي للعمل الرقمي المفيد أن يربط المؤسس بحاسوبه المحمول.", [["Sworder وNeo", "ربط النظام الأول Meta Ads وCloudflare وخادمًا بتجربة ذكاء اصطناعي تُدار عبر Telegram. أنجز عملًا مفيدًا، لكنه بقي مخصصًا وتفاعليًا ومكلفًا للتشغيل الآمن."], ["سبب إنساني", "أثناء حمل زوجة Juliano، كان للتحرر من الحاسوب معنى ملموس: حضور أكبر مع العائلة دون التخلي عن مسؤولية العمل."], ["أطروحة Shimpz", "ينبغي للاستدلال أن ينسق برمجيات محدودة وقابلة لإعادة الاستخدام بدل اختراع كل تنفيذ من جديد. يحتفظ البشر بالسلطة على الوصول والقرارات المؤثرة."]], "منظمة ومشروع", "تقدم Shimpz الشركة والعمل مفتوح المصدر بصوت واحد: دقيق بشأن الموجود، وصريح بشأن المستقبل، ومنظم كي يتجاوز المنتج جلسة واحدة أو ذاكرة شخص واحد."],
  }),
};

export function institutionalPage(page: InstitutionalPage, locale: Locale): InstitutionalPageContent {
  return PAGE_CONTENT[page][locale];
}
